name: Build and deploy Fringe.API to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Fringe/Fringe.API/Fringe.API.csproj

      - name: Build with dotnet
        run: dotnet build Fringe/Fringe.API/Fringe.API.csproj --configuration Release --no-restore

      - name: Publish Fringe.API
        run: dotnet publish Fringe/Fringe.API/Fringe.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fringe-api
          path: ${{env.DOTNET_ROOT}}/app

  deploy:
    # The rest of your deployment job remains unchanged
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fringe-api

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fringebackendtest'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CCB30456CE44F5D9DCA0643FAA1DD95 }}